export const USER_INFO = 'USER_INFO'
export const CURRENT_MODULE = 'CURRENT_MODULE'
export const NEED_SHOW_LOGIN_POP = 'NEED_SHOW_LOGIN_POP'
export const STORE_AUTH = 'STORE_AUTH'
export const IS_ADMIN = 'IS_ADMIN'
export const LEFTBAR_CHANGE = 'LEFTBAR_CHANGE'
export const HAS_LEFTBAR = 'HAS_LEFTBAR'
export const MENU_LIST = 'MENU_LIST'
